export const level5 = {
    width: 10,
    height: 10,
    tileSize: 5,
    robotX: 3,
    robotZ: 0,
    robotRotation: 'Forward',
    cubes: [
        {
            x: 2,
            y: 0,
            z: 5,
        },
        {
            x: 4,
            y: 0,
            z: 5,
        },
        {
            x: 4,
            y: 0,
            z: 6,
        },
        {
            x: 5,
            y: 0,
            z: 6,
        },
        {
            x: 5,
            y: 0,
            z: 7,
        },
        {
            x: 6,
            y: 0,
            z: 7,
        },
        {
            x: 7,
            y: 0,
            z: 7,
        },
        {
            x: 8,
            y: 0,
            z: 5,
        },
        {
            x: 9,
            y: 0,
            z: 5,
        },
        {
            x: 7,
            y: 0,
            z: 8,
        },
        {
            x: 6,
            y: 0,
            z: 8,
        },
        {
            x: 8,
            y: 0,
            z: 8,
        },
        {
            x: 3,
            y: 0,
            z: 9,
        },
        {
            x: 3,
            y: 0,
            z: 8,
        },
        {
            x: 2,
            y: 0,
            z: 7,
        },
        {
            x: 1,
            y: 0,
            z: 7,
        },
        {
            x: 2,
            y: 0,
            z: 8,
        },
        {
            x: 0,
            y: 0,
            z: 5,
        },
        {
            x: 0,
            y: 0,
            z: 4,
        },
        {
            x: 0,
            y: 0,
            z: 3,
        },
        {
            x: 1,
            y: 0,
            z: 3,
        },
        {
            x: 2,
            y: 0,
            z: 3,
        },
        {
            x: 3,
            y: 0,
            z: 3,
        },
        {
            x: 2,
            y: 0,
            z: 1,
        },
        {
            x: 3,
            y: 0,
            z: 1,
        },
        {
            x: 0,
            y: 0,
            z: 1,
        },
        {
            x: 4,
            y: 0,
            z: 1,
        },
        {
            x: 5,
            y: 0,
            z: 1,
        },
        {
            x: 5,
            y: 0,
            z: 2,
        },
        {
            x: 6,
            y: 0,
            z: 2,
        },
        {
            x: 7,
            y: 0,
            z: 0,
        },
        {
            x: 8,
            y: 0,
            z: 0,
        },
        {
            x: 9,
            y: 0,
            z: 0,
        },
        {
            x: 8,
            y: 0,
            z: 2,
        },
    ],
    endX: 8,
    endZ: 9,
    enemies: [
        {
            x: 3,
            y: 0,
            z: 5,
            rotation: 0,
            sightDistance: 15,
            hearingDistance: 0,
            speed: 0,
        },
        {
            x: 5,
            y: 0,
            z: 5,
            rotation: 0,
            sightDistance: 15,
            hearingDistance: 0,
            speed: 0,
        },
        {
            x: 7,
            y: 0,
            z: 5,
            rotation: 0,
            sightDistance: 15,
            hearingDistance: 0,
            speed: 0,
        },
        {
            x: 9,
            y: 0,
            z: 6,
            rotation: -90,
            sightDistance: 15,
            hearingDistance: 0,
            speed: 0,
        },
        {
            x: 8,
            y: 0,
            z: 7,
            rotation: 0,
            sightDistance: 15,
            hearingDistance: 0,
            speed: 0,
        },
        {
            x: 7,
            y: 0,
            z: 9,
            rotation: -90,
            sightDistance: 15,
            hearingDistance: 0,
            speed: 0,
        },
        {
            x: 4,
            y: 0,
            z: 9,
            rotation: 0,
            sightDistance: 15,
            hearingDistance: 0,
            speed: 0,
        },
        {
            x: 2,
            y: 0,
            z: 2,
            rotation: -90,
            sightDistance: 15,
            hearingDistance: 0,
            speed: 0,
        },
        {
            x: 0,
            y: 0,
            z: 9,
            rotation: 90,
            sightDistance: 15,
            hearingDistance: 0,
            speed: 0,
        },
        {
            x: 0,
            y: 0,
            z: 0,
            rotation: 90,
            sightDistance: 15,
            hearingDistance: 0,
            speed: 0,
        },
        {
            x: 7,
            y: 0,
            z: 3,
            rotation: 0,
            sightDistance: 15,
            hearingDistance: 0,
            speed: 0,
        },
        {
            x: 9,
            y: 0,
            z: 4,
            rotation: -50,
            sightDistance: 15,
            hearingDistance: 0,
            speed: 0,
        }
    ]
}